# Дефолтный сервер (заглушка)
server {
    listen 80 default_server;
    server_name _;
    return 404;
}

server {
    listen 80;
    server_name sqli.vulnforge.local;

    location / {
        proxy_pass http://vf-sqli:80;
        proxy_set_header Host sqli.vulnforge.local;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 80;
    server_name xss.vulnforge.local;

    location / {
        proxy_pass http://vf-xss:80;
        proxy_set_header Host xss.vulnforge.local;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
